# Generated by Django 3.1.7 on 2021-08-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=10)),
                ('subcategory', models.CharField(max_length=10)),
                ('release_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
